import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ArrowRight, Boxes, ClipboardList, PackageSearch, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge } from '../components/ui/badge';
import { Card } from '../components/ui/card';
import { CardSkeletons, ErrorState, TableSkeleton } from '../components/ui/states';
import { PageHeader } from '../components/PageHeader';
import { dashboardService } from '../services/dashboard.service';
import { currency, date, dateTime } from '../lib/utils';
import type { ChallanStatus } from '../types';

const statusTone: Record<ChallanStatus, 'info' | 'success' | 'danger'> = { DRAFT: 'info', CONFIRMED: 'success', CANCELLED: 'danger' };
function StatCard({ label, value, description, icon: Icon, tone }: { label: string; value: number; description: string; icon: typeof Users; tone: 'navy' | 'amber' | 'red' | 'blue' }) { const tones = { navy: 'bg-navy-50 text-navy-800', amber: 'bg-amber-50 text-amber-700', red: 'bg-red-50 text-red-700', blue: 'bg-blue-50 text-blue-700' }; return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-ink">{value}</p></div><div className={`rounded-lg p-2.5 ${tones[tone]}`}><Icon className="h-5 w-5" /></div></div><p className="mt-3 text-xs text-slate-500">{description}</p></Card>; }

export function DashboardPage() {
  const stats = useQuery({ queryKey: ['dashboard'], queryFn: dashboardService.stats });
  if (stats.isLoading) return <><PageHeader title="Dashboard" description="Overview of your business operations." /><CardSkeletons /><div className="surface mt-6"><TableSkeleton /></div></>;
  if (stats.isError || !stats.data) return <ErrorState message="We couldn't load your business overview." retry={() => stats.refetch()} />;
  const data = stats.data;
  return <><PageHeader title="Dashboard" description="Overview of your business operations." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total Customers" value={data.totalCustomers} description="Customer records across all statuses" icon={Users} tone="navy" /><StatCard label="Total Products" value={data.totalProducts} description="Products available in your catalogue" icon={PackageSearch} tone="blue" /><StatCard label="Low Stock" value={data.lowStockProducts} description="Products at or below their stock threshold" icon={AlertTriangle} tone="red" /><StatCard label="Pending Follow-ups" value={data.pendingFollowUps} description="Customer follow-ups scheduled from today" icon={ClipboardList} tone="amber" /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_.95fr]"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-ink">Recent Challans</h2><p className="mt-0.5 text-xs text-slate-500">Latest dispatch documents from the API</p></div><Link to="/challans" className="inline-flex items-center gap-1 text-xs font-semibold text-navy-700 hover:text-navy-900">View all <ArrowRight className="h-3.5 w-3.5" /></Link></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Challan</th><th>Customer</th><th className="text-right">Qty</th><th>Status</th><th>Created</th></tr></thead><tbody>{data.recentChallans.map((challan) => <tr key={challan.id}><td><Link to={`/challans/${challan.id}`} className="font-medium text-navy-800 hover:underline">{challan.challanNumber}</Link><p className="mt-0.5 text-xs text-slate-400">{challan._count.items} item{challan._count.items === 1 ? '' : 's'}</p></td><td><p className="font-medium text-slate-700">{challan.customer.customerName}</p><p className="mt-0.5 text-xs text-slate-400">{challan.customer.businessName}</p></td><td className="text-right font-medium tabular-nums">{challan.totalQuantity}</td><td><Badge tone={statusTone[challan.status]}>{challan.status[0] + challan.status.slice(1).toLowerCase()}</Badge></td><td className="whitespace-nowrap text-xs text-slate-500">{date(challan.createdAt)}</td></tr>)}</tbody></table></div>{data.recentChallans.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No challans have been created yet.</p>}</Card>
      <div className="space-y-6"><Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-semibold text-ink">Low Stock Products</h2><p className="mt-0.5 text-xs text-slate-500">Requires attention</p></div><Link to="/products?lowStock=true" className="text-xs font-semibold text-navy-700">View products</Link></div><div>{data.lowStockItems.length ? data.lowStockItems.map((product) => <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3 last:border-0" key={product.id}><div><p className="font-medium text-slate-700">{product.productName}</p><p className="mt-0.5 text-xs text-slate-400">{product.sku} · {product.warehouseLocation}</p></div><p className="text-sm font-semibold text-red-700">{product.currentStock} <span className="text-xs font-normal">/ min {product.minimumStockQuantity}</span></p></div>) : <p className="px-5 py-7 text-center text-sm text-slate-500">All product stock levels are healthy.</p>}</div></Card>
        <Card className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-ink">Upcoming Follow-ups</h2><p className="mt-0.5 text-xs text-slate-500">Next conversations with customers</p></div><div>{data.upcomingFollowUps.length ? data.upcomingFollowUps.map((customer) => <Link to={`/customers/${customer.id}`} className="flex items-center justify-between border-b border-slate-100 px-5 py-3 transition-colors hover:bg-slate-50 last:border-0" key={customer.id}><div><p className="font-medium text-slate-700">{customer.customerName}</p><p className="mt-0.5 text-xs text-slate-400">{customer.businessName}</p></div><p className="text-xs font-medium text-slate-500">{date(customer.followUpDate)}</p></Link>) : <p className="px-5 py-7 text-center text-sm text-slate-500">No follow-ups scheduled.</p>}</div></Card></div></div>
    <Card className="mt-6 overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-ink">Recent Inventory Activity</h2><p className="mt-0.5 text-xs text-slate-500">Latest stock movement audit records</p></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Movement</th><th className="text-right">Quantity</th><th>Reason</th><th>Created</th></tr></thead><tbody>{data.recentStockMovements.map((movement) => <tr key={movement.id}><td><p className="font-medium text-slate-700">{movement.product.productName}</p><p className="text-xs text-slate-400">{movement.product.sku}</p></td><td><Badge tone={movement.movementType === 'IN' ? 'success' : 'info'}>{movement.movementType}</Badge></td><td className={`text-right font-semibold tabular-nums ${movement.movementType === 'IN' ? 'text-emerald-700' : 'text-slate-700'}`}>{movement.movementType === 'IN' ? '+' : '−'}{movement.quantity}</td><td className="max-w-80 truncate text-slate-500">{movement.reason}</td><td className="whitespace-nowrap text-xs text-slate-500">{dateTime(movement.createdAt)}</td></tr>)}</tbody></table></div></Card></>;
}
