import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDownLeft, ArrowUpRight, Plus, Search, Warehouse } from 'lucide-react';
import { PageHeader } from '../components/PageHeader';
import { Button } from '../components/ui/button';
import { Dialog } from '../components/ui/dialog';
import { Badge } from '../components/ui/badge';
import { EmptyState, ErrorState, TableSkeleton } from '../components/ui/states';
import { productService } from '../services/product.service';
import { inventoryService } from '../services/inventory.service';
import { ApiError } from '../services/api';
import { dateTime } from '../lib/utils';
import { useToast } from '../components/ToastProvider';

function MovementDialog({ onClose }: { onClose: () => void }) {
  const products = useQuery({ queryKey: ['products-all'], queryFn: () => productService.list({ page: 1, limit: 100 }) });
  const [productId, setProductId] = useState(''); const [movementType, setMovementType] = useState<'IN'|'OUT'>('IN'); const [quantity, setQuantity] = useState(1); const [reason, setReason] = useState('');
  const client = useQueryClient(); const toast = useToast();
  const mutation = useMutation({ mutationFn: () => inventoryService.create({ productId, movementType, quantity, reason }), onSuccess: () => { client.invalidateQueries({ queryKey: ['inventory'] }); client.invalidateQueries({ queryKey: ['products'] }); client.invalidateQueries({ queryKey: ['dashboard'] }); toast.success('Stock movement recorded'); onClose(); }, onError: e => toast.error(e instanceof ApiError ? e.message : 'Could not record movement') });
  return <Dialog open title="Record stock movement" description="Every adjustment is written to the inventory audit trail." onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button loading={mutation.isPending} onClick={() => mutation.mutate()} disabled={!productId || !reason.trim()}>Record movement</Button></>}><div className="space-y-4"><div><label className="field-label">Product</label><select className="field-control" value={productId} onChange={e => setProductId(e.target.value)}><option value="">Select product</option>{products.data?.data.map(p => <option key={p.id} value={p.id}>{p.productName} · {p.sku} · {p.currentStock} in stock</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="field-label">Movement</label><select className="field-control" value={movementType} onChange={e => setMovementType(e.target.value as 'IN'|'OUT')}><option value="IN">Stock in</option><option value="OUT">Stock out</option></select></div><div><label className="field-label">Quantity</label><input className="field-control" type="number" min="1" value={quantity} onChange={e => setQuantity(Math.max(1, Number(e.target.value)))} /></div></div><div><label className="field-label">Reason</label><textarea className="field-control h-24 py-2.5" placeholder="Purchase receipt, damage, manual adjustment…" value={reason} onChange={e => setReason(e.target.value)} /></div></div></Dialog>;
}

export function InventoryPage() {
  const [page, setPage] = useState(1); const [movementType, setMovementType] = useState<'IN'|'OUT'|''>(''); const [search, setSearch] = useState(''); const [open, setOpen] = useState(false);
  const products = useQuery({ queryKey: ['products-inventory'], queryFn: () => productService.list({ page: 1, limit: 100 }) });
  const productId = useMemo(() => products.data?.data.find(p => p.productName.toLowerCase().includes(search.toLowerCase()) || p.sku.toLowerCase().includes(search.toLowerCase()))?.id, [products.data, search]);
  const movements = useQuery({ queryKey: ['inventory', page, movementType, productId], queryFn: () => inventoryService.list({ page, limit: 15, movementType: movementType || undefined, productId }) });
  return <><PageHeader eyebrow="Warehouse" title="Inventory" description="Monitor stock movements and keep a reliable operational audit trail." actions={<Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Record movement</Button>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="surface p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Products tracked</p><p className="metric-value mt-1 text-2xl font-extrabold text-slate-900">{products.data?.pagination.total ?? '—'}</p></div><div className="surface p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Current view</p><p className="mt-1 text-sm font-bold text-slate-900">{movementType === 'IN' ? 'Stock received' : movementType === 'OUT' ? 'Stock issued' : 'All movements'}</p></div><div className="surface p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Control</p><p className="mt-1 flex items-center gap-1.5 text-sm font-bold text-emerald-700"><Warehouse className="h-4 w-4" />Audit ready</p></div></div>
    <section className="surface overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input className="field-control pl-9" placeholder="Find a product…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div><select className="field-control lg:w-48" value={movementType} onChange={e => { setMovementType(e.target.value as 'IN'|'OUT'|''); setPage(1); }}><option value="">All movement types</option><option value="IN">Stock in</option><option value="OUT">Stock out</option></select></div>{movements.isLoading ? <TableSkeleton /> : movements.isError || !movements.data ? <ErrorState message="We couldn't load inventory movements." retry={() => movements.refetch()} /> : movements.data.data.length === 0 ? <EmptyState title="No movements found" description="Inventory activity will appear here after stock is received, issued or adjusted." action={<Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Record movement</Button>} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Movement</th><th className="text-right">Quantity</th><th>Reason</th><th>Recorded by</th><th>Time</th></tr></thead><tbody>{movements.data.data.map(m => <tr key={m.id}><td><p className="font-bold text-slate-800">{m.product.productName}</p><p className="text-xs text-slate-400">{m.product.sku}</p></td><td><Badge tone={m.movementType === 'IN' ? 'success' : 'info'}>{m.movementType === 'IN' ? <><ArrowDownLeft className="mr-1 inline h-3.5 w-3.5" />IN</> : <><ArrowUpRight className="mr-1 inline h-3.5 w-3.5" />OUT</>}</Badge></td><td className={m.movementType === 'IN' ? 'text-right font-bold text-emerald-700' : 'text-right font-bold text-slate-700'}>{m.movementType === 'IN' ? '+' : '−'}{m.quantity}</td><td className="max-w-[28rem] truncate text-slate-500">{m.reason}</td><td className="text-slate-600">{m.createdBy.name}</td><td className="whitespace-nowrap text-xs text-slate-400">{dateTime(m.createdAt)}</td></tr>)}</tbody></table></div>}</section>{movements.data && movements.data.pagination.totalPages > 1 && <div className="mt-4 flex justify-end gap-2"><Button variant="secondary" size="sm" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</Button><span className="flex h-8 items-center px-2 text-xs font-semibold text-slate-500">Page {page} of {movements.data.pagination.totalPages}</span><Button variant="secondary" size="sm" disabled={page >= movements.data.pagination.totalPages} onClick={() => setPage(p => p + 1)}>Next</Button></div>}{open && <MovementDialog onClose={() => setOpen(false)} />}</>;
}
