import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Edit3, PackagePlus, Plus, Search, Boxes } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Dialog } from '../components/ui/dialog';
import { Badge } from '../components/ui/badge';
import { EmptyState, ErrorState, TableSkeleton } from '../components/ui/states';
import { PageHeader } from '../components/PageHeader';
import { productService, type ProductInput } from '../services/product.service';
import { ApiError } from '../services/api';
import { useAuth } from '../hooks/useAuth';
import { currency, date } from '../lib/utils';
import type { Product } from '../types';
import { useToast } from '../components/ToastProvider';

const emptyProduct: ProductInput = { productName: '', sku: '', category: '', unitPrice: 0, currentStock: 0, minimumStockQuantity: 0, warehouseLocation: '' };

function ProductDialog({ product, onClose }: { product?: Product; onClose: () => void }) {
  const [form, setForm] = useState<ProductInput>(product ? { productName: product.productName, sku: product.sku, category: product.category, unitPrice: Number(product.unitPrice), currentStock: product.currentStock, minimumStockQuantity: product.minimumStockQuantity, warehouseLocation: product.warehouseLocation } : emptyProduct);
  const queryClient = useQueryClient(); const toast = useToast();
  const mutation = useMutation({ mutationFn: () => product ? productService.update(product.id, form) : productService.create(form), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['products'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); toast.success(product ? 'Product updated' : 'Product added'); onClose(); }, onError: (e) => toast.error(e instanceof ApiError ? e.message : 'Could not save product') });
  const set = (key: keyof ProductInput, value: string) => setForm((current) => ({ ...current, [key]: ['unitPrice','currentStock','minimumStockQuantity'].includes(key) ? Number(value) : value } as ProductInput));
  return <Dialog open title={product ? 'Edit product' : 'Add product'} description="Keep catalogue and warehouse information accurate for the whole team." onClose={onClose} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button loading={mutation.isPending} onClick={() => mutation.mutate()}>{product ? 'Save changes' : 'Create product'}</Button></>}>
    <div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><label className="field-label">Product name</label><input className="field-control" value={form.productName} onChange={e => set('productName', e.target.value)} /></div><div><label className="field-label">SKU</label><input className="field-control uppercase" value={form.sku} onChange={e => set('sku', e.target.value)} /></div><div><label className="field-label">Category</label><input className="field-control" value={form.category} onChange={e => set('category', e.target.value)} /></div><div><label className="field-label">Unit price</label><input className="field-control" type="number" min="0" step="0.01" value={form.unitPrice} onChange={e => set('unitPrice', e.target.value)} /></div><div><label className="field-label">Warehouse location</label><input className="field-control" value={form.warehouseLocation} onChange={e => set('warehouseLocation', e.target.value)} /></div><div><label className="field-label">Current stock</label><input className="field-control" type="number" min="0" value={form.currentStock} onChange={e => set('currentStock', e.target.value)} /></div><div><label className="field-label">Minimum stock</label><input className="field-control" type="number" min="0" value={form.minimumStockQuantity} onChange={e => set('minimumStockQuantity', e.target.value)} /></div></div>
  </Dialog>;
}

export function ProductsPage() {
  const { can } = useAuth(); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [lowStock, setLowStock] = useState(false); const [page, setPage] = useState(1); const [editing, setEditing] = useState<Product>();
  const filters = useMemo(() => ({ page, limit: 12, search: search || undefined, category: category || undefined, lowStock: lowStock || undefined }), [page, search, category, lowStock]);
  const products = useQuery({ queryKey: ['products', filters], queryFn: () => productService.list(filters) });
  const categories = useQuery({ queryKey: ['product-categories'], queryFn: productService.categories });
  return <><PageHeader eyebrow="Catalogue" title="Products" description="Control your product catalogue, pricing and warehouse stock thresholds." actions={can('ADMIN','WAREHOUSE') ? <Button onClick={() => setEditing(null as unknown as Product)}><Plus className="h-4 w-4" />Add product</Button> : undefined} />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="surface flex items-center gap-3 p-4"><div className="rounded-xl bg-indigo-50 p-2.5 text-indigo-700"><Boxes className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Catalogue</p><p className="metric-value mt-0.5 text-xl font-extrabold text-slate-900">{products.data?.pagination.total ?? '—'}</p></div></div><div className="surface flex items-center gap-3 p-4"><div className="rounded-xl bg-amber-50 p-2.5 text-amber-700"><AlertTriangle className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Low stock view</p><p className="mt-0.5 text-sm font-bold text-slate-900">{lowStock ? 'Filtered' : 'All products'}</p></div></div><div className="surface flex items-center gap-3 p-4"><div className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700"><PackagePlus className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Categories</p><p className="metric-value mt-0.5 text-xl font-extrabold text-slate-900">{categories.data?.length ?? '—'}</p></div></div></div>
    <section className="surface overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 lg:flex-row"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input className="field-control pl-9" placeholder="Search by product name or SKU…" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} /></div><select className="field-control lg:w-48" value={category} onChange={e => { setCategory(e.target.value); setPage(1); }}><option value="">All categories</option>{categories.data?.map(c => <option key={c.category} value={c.category}>{c.category}</option>)}</select><button className={lowStock ? 'h-10 rounded-xl border border-red-200 bg-red-50 px-4 text-sm font-semibold text-red-700' : 'h-10 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-600'} onClick={() => { setLowStock(v => !v); setPage(1); }}>Low stock only</button></div>
      {products.isLoading ? <TableSkeleton /> : products.isError || !products.data ? <ErrorState message="We couldn't load the product catalogue." retry={() => products.refetch()} /> : products.data.data.length === 0 ? <EmptyState title="No products found" description="Try a different search or add the first product to your catalogue." action={can('ADMIN','WAREHOUSE') ? <Button onClick={() => setEditing(null as unknown as Product)}><Plus className="h-4 w-4" />Add product</Button> : undefined} /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Category</th><th>Location</th><th className="text-right">Price</th><th className="text-right">Stock</th><th>Updated</th><th /></tr></thead><tbody>{products.data.data.map(p => { const low = p.currentStock <= p.minimumStockQuantity; return <tr key={p.id}><td><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 text-slate-500"><PackagePlus className="h-4 w-4" /></div><div><p className="font-bold text-slate-800">{p.productName}</p><p className="mt-0.5 text-xs font-medium text-slate-400">{p.sku}</p></div></div></td><td className="text-slate-600">{p.category}</td><td className="text-slate-600">{p.warehouseLocation}</td><td className="text-right font-semibold tabular-nums">{currency(p.unitPrice)}</td><td className="text-right"><span className={low ? 'font-bold text-red-700' : 'font-semibold text-slate-700'}>{p.currentStock}</span><span className="ml-1 text-xs text-slate-400">/ {p.minimumStockQuantity} min</span></td><td className="text-xs text-slate-500">{date(p.updatedAt)}</td><td className="text-right">{can('ADMIN','WAREHOUSE') && <button className="inline-flex h-8 items-center gap-1 rounded-lg px-2 text-xs font-semibold text-slate-500 hover:bg-slate-100" onClick={() => setEditing(p)}><Edit3 className="h-3.5 w-3.5" />Edit</button>}{low && <Badge tone="danger">Low</Badge>}</td></tr>})}</tbody></table></div>}
    </section>{products.data && products.data.pagination.totalPages > 1 && <div className="mt-4 flex justify-end gap-2"><Button variant="secondary" size="sm" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Previous</Button><span className="flex h-8 items-center px-2 text-xs font-semibold text-slate-500">Page {page} of {products.data.pagination.totalPages}</span><Button variant="secondary" size="sm" disabled={page >= products.data.pagination.totalPages} onClick={() => setPage(p => p + 1)}>Next</Button></div>}
    {editing !== undefined && <ProductDialog product={editing || undefined} onClose={() => setEditing(undefined)} />}</>;
}
